# Generated by Django 3.2.3 on 2021-06-01 15:07

import StockDashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='WatchlistPerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('stockCode', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('isWatchList', models.BooleanField(default=True)),
                ('isOwned', models.BooleanField(default=True)),
                ('trade_date', models.DateTimeField(default=StockDashboard.models.default_date)),
                ('trade_cost', models.IntegerField()),
            ],
        ),
    ]
